"""
Playwright Regression Test Generator.
Converts recorded crawl action traces and captured network calls into runnable
Playwright regression test suites (Python pytest-playwright and TypeScript @playwright/test).
"""
from __future__ import annotations

import io
import json
import re
import zipfile
from typing import List, Dict, Any, Optional
from urllib.parse import urlparse


class PlaywrightTestGenerator:
    """
    Generates runnable Playwright regression test scripts and multi-file test suites
    with network status code assertions and response schema contract validations.
    """

    @classmethod
    def _sanitize_string(cls, val: Any) -> str:
        """Escape quotes and backslashes for code injection safety."""
        if val is None:
            return ""
        s = str(val).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "")
        return s

    @classmethod
    def _extract_url_path_fragment(cls, url: str) -> str:
        """Extract a distinct path fragment from URL for expect_response matchers."""
        try:
            parsed = urlparse(url)
            path = parsed.path
            if path and path != "/":
                return path
            return parsed.netloc
        except Exception:
            return url

    @classmethod
    def _extract_top_level_keys(cls, body: Any, max_keys: int = 6) -> List[str]:
        """Extract top-level keys from response body for schema contract assertions."""
        if isinstance(body, dict):
            return list(body.keys())[:max_keys]
        elif isinstance(body, list) and body and isinstance(body[0], dict):
            return list(body[0].keys())[:max_keys]
        return []

    # ── Python / Pytest Generator ─────────────────────────────────────────────

    @classmethod
    def generate_python_test(
        cls,
        target_url: str,
        action_traces: List[Dict[str, Any]],
        session_id: str = "crawl-session",
    ) -> str:
        """Generates runnable pytest-playwright test code."""
        sanitized_target = cls._sanitize_string(target_url)
        lines = [
            '"""',
            f"Playwright Python Regression Test Suite — Generated by InsightAPI AI",
            f"Target URL: {target_url}",
            f"Session ID: {session_id}",
            f"Total Actions: {len(action_traces)}",
            '"""',
            "import json",
            "import pytest",
            "from playwright.sync_api import Page, expect",
            "",
            "",
            "@pytest.mark.regression",
            f"def test_api_regression_flow(page: Page):",
            f'    """Replay discovered crawl actions and assert API contract stability."""',
            f'    print("\\n[InsightAPI] Starting regression test on: {sanitized_target}")',
            "",
            f"    # Step 0: Initial Navigation",
            f'    page.goto("{sanitized_target}", wait_until="networkidle", timeout=30000)',
            f'    expect(page).to_have_title(re.compile(r".+"))',
            "",
        ]

        if not action_traces:
            lines.append("    # No dynamic interactions recorded during crawl; base page loaded successfully.")
            lines.append("    assert page.url is not None")
            return "\n".join(lines) + "\n"

        for idx, trace in enumerate(action_traces, start=1):
            action_type = (trace.get("action_type") or "click").lower()
            selector = cls._sanitize_string(trace.get("selector") or "")
            value = cls._sanitize_string(trace.get("value") or "")
            network_calls = trace.get("network_calls_triggered") or []
            url_after = cls._sanitize_string(trace.get("url_after") or "")

            if not selector and action_type not in ("navigate", "goto"):
                continue

            lines.append(f"    # ── Step {idx}: Action [{action_type.upper()}] on `{selector}` ──")

            # Determine primary network call to assert on (if any)
            target_call = network_calls[0] if network_calls else None

            if target_call and target_call.get("url"):
                method = target_call.get("method", "GET").upper()
                expected_status = target_call.get("status", 200)
                path_frag = cls._sanitize_string(cls._extract_url_path_fragment(target_call.get("url", "")))
                top_keys = cls._extract_top_level_keys(target_call.get("response_body"))

                lines.append(
                    f'    # Expect {method} API response matching path `{path_frag}` with status {expected_status}'
                )
                lines.append(
                    f'    with page.expect_response('
                    f'lambda r: "{path_frag}" in r.url and r.status == {expected_status}, '
                    f'timeout=15000) as resp_info_{idx}:'
                )

                # Indented action execution inside expect_response context
                action_code = cls._format_python_action(action_type, selector, value)
                lines.append(f"        {action_code}")
                lines.append("")
                lines.append(f"    resp_{idx} = resp_info_{idx}.value")
                lines.append(f"    assert resp_{idx}.status == {expected_status}, f'Unexpected status: {{resp_{idx}.status}}'")

                # Schema contract assertions on response body
                if top_keys:
                    lines.append(f"    try:")
                    lines.append(f"        data_{idx} = resp_{idx}.json()")
                    for k in top_keys:
                        sanitized_k = cls._sanitize_string(k)
                        lines.append(
                            f'        assert "{sanitized_k}" in data_{idx}, '
                            f"'Regression failure: missing expected field `{sanitized_k}` in response body'"
                        )
                    lines.append(f"    except Exception as e:")
                    lines.append(f'        print(f"Warning: Response JSON verification skipped for step {idx}: {{e}}")')

            else:
                # No API call directly tied to this action
                action_code = cls._format_python_action(action_type, selector, value)
                lines.append(f"    {action_code}")
                lines.append(f'    page.wait_for_load_state("networkidle")')

            lines.append("")

        lines.append("    print('[InsightAPI] ✓ All user actions and API contract assertions passed!')")
        return "\n".join(lines) + "\n"

    @classmethod
    def _format_python_action(cls, action_type: str, selector: str, value: str) -> str:
        if action_type in ("fill", "type", "input"):
            return f'page.fill("{selector}", "{value or "test-value"}")'
        elif action_type in ("check", "checkbox"):
            return f'page.check("{selector}")'
        elif action_type in ("select", "select_option"):
            if value:
                return f'page.select_option("{selector}", value="{value}")'
            return f'page.select_option("{selector}", index=0)'
        elif action_type == "hover":
            return f'page.hover("{selector}")'
        elif action_type == "press":
            key = value if value else "Enter"
            return f'page.press("{selector}", "{key}")'
        else:
            return f'page.click("{selector}")'

    # ── TypeScript / @playwright/test Generator ──────────────────────────────

    @classmethod
    def generate_typescript_test(
        cls,
        target_url: str,
        action_traces: List[Dict[str, Any]],
        session_id: str = "crawl-session",
    ) -> str:
        """Generates runnable @playwright/test TypeScript code."""
        sanitized_target = cls._sanitize_string(target_url)
        lines = [
            "/**",
            f" * Playwright TypeScript Regression Test Suite — Generated by InsightAPI AI",
            f" * Target URL: {target_url}",
            f" * Session ID: {session_id}",
            f" * Total Actions: {len(action_traces)}",
            " */",
            "import { test, expect } from '@playwright/test';",
            "",
            "test.describe('InsightAPI Discovered Regression Suite', () => {",
            "  test('replays discovered crawl actions and asserts API contract', async ({ page }) => {",
            f"    console.log('[InsightAPI] Starting regression test on: {sanitized_target}');",
            "",
            f"    // Step 0: Initial Navigation",
            f"    await page.goto('{sanitized_target}', {{ waitUntil: 'networkidle', timeout: 30000 }});",
            f"    await expect(page).toHaveTitle(/.+/);",
            "",
        ]

        if not action_traces:
            lines.append("    // No dynamic interactions recorded during crawl; base page loaded successfully.")
            lines.append("    expect(page.url()).toBeTruthy();")
            lines.append("  });")
            lines.append("});")
            return "\n".join(lines) + "\n"

        for idx, trace in enumerate(action_traces, start=1):
            action_type = (trace.get("action_type") or "click").lower()
            selector = cls._sanitize_string(trace.get("selector") or "")
            value = cls._sanitize_string(trace.get("value") or "")
            network_calls = trace.get("network_calls_triggered") or []

            if not selector and action_type not in ("navigate", "goto"):
                continue

            lines.append(f"    // ── Step {idx}: Action [{action_type.upper()}] on `{selector}` ──")
            target_call = network_calls[0] if network_calls else None

            if target_call and target_call.get("url"):
                method = target_call.get("method", "GET").upper()
                expected_status = target_call.get("status", 200)
                path_frag = cls._sanitize_string(cls._extract_url_path_fragment(target_call.get("url", "")))
                top_keys = cls._extract_top_level_keys(target_call.get("response_body"))

                action_ts = cls._format_ts_action(action_type, selector, value)

                lines.append(
                    f"    // Expect {method} API response matching path `{path_frag}` with status {expected_status}"
                )
                lines.append(f"    const [response{idx}] = await Promise.all([")
                lines.append(
                    f"      page.waitForResponse(res => res.url().includes('{path_frag}') && res.status() === {expected_status}, {{ timeout: 15000 }}),"
                )
                lines.append(f"      {action_ts},")
                lines.append("    ]);")
                lines.append("")
                lines.append(f"    expect(response{idx}.status()).toBe({expected_status});")

                if top_keys:
                    lines.append(f"    const data{idx} = await response{idx}.json().catch(() => null);")
                    lines.append(f"    if (data{idx}) {{")
                    for k in top_keys:
                        sanitized_k = cls._sanitize_string(k)
                        lines.append(f"      expect(data{idx}).toHaveProperty('{sanitized_k}');")
                    lines.append("    }")

            else:
                action_ts = cls._format_ts_action(action_type, selector, value)
                lines.append(f"    await {action_ts};")
                lines.append("    await page.waitForLoadState('networkidle');")

            lines.append("")

        lines.append("    console.log('[InsightAPI] ✓ All user actions and API contract assertions passed!');")
        lines.append("  });")
        lines.append("});")
        return "\n".join(lines) + "\n"

    @classmethod
    def _format_ts_action(cls, action_type: str, selector: str, value: str) -> str:
        if action_type in ("fill", "type", "input"):
            return f"page.fill('{selector}', '{value or 'test-value'}')"
        elif action_type in ("check", "checkbox"):
            return f"page.check('{selector}')"
        elif action_type in ("select", "select_option"):
            if value:
                return f"page.selectOption('{selector}', '{value}')"
            return f"page.selectOption('{selector}', {{ index: 0 }})"
        elif action_type == "hover":
            return f"page.hover('{selector}')"
        elif action_type == "press":
            key = value if value else "Enter"
            return f"page.press('{selector}', '{key}')"
        else:
            return f"page.click('{selector}')"

    # ── Zip Archive Package Generator ─────────────────────────────────────────

    @classmethod
    def generate_test_suite_zip(
        cls,
        target_url: str,
        action_traces: List[Dict[str, Any]],
        session_id: str = "crawl-session",
        format: str = "python",
    ) -> bytes:
        """Packages runnable test suite with configs and README into in-memory zip bytes."""
        zip_buf = io.BytesIO()

        with zipfile.ZipFile(zip_buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            if format.lower() in ("ts", "typescript"):
                # TypeScript Suite
                ts_code = cls.generate_typescript_test(target_url, action_traces, session_id)
                zf.writestr("tests/regression.spec.ts", ts_code)

                # playwright.config.ts
                playwright_config = """import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 30 * 1000,
  expect: {
    timeout: 10000,
  },
  fullyParallel: true,
  reporter: [['html'], ['list']],
  use: {
    baseURL: '""" + target_url + """',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
"""
                zf.writestr("playwright.config.ts", playwright_config)

                # package.json
                package_json = {
                    "name": "insightapi-regression-suite",
                    "version": "1.0.0",
                    "description": f"Automated Playwright regression tests for {target_url}",
                    "scripts": {
                        "test": "playwright test",
                        "test:headed": "playwright test --headed",
                        "test:ui": "playwright test --ui",
                    },
                    "devDependencies": {
                        "@playwright/test": "^1.42.0",
                        "@types/node": "^20.0.0",
                        "typescript": "^5.0.0",
                    },
                }
                zf.writestr("package.json", json.dumps(package_json, indent=2))

                # README.md
                readme = f"""# InsightAPI Playwright TypeScript Regression Suite

Auto-generated regression test suite for **{target_url}**.

## Prerequisites
- Node.js 18+

## Quick Start
```bash
npm install
npx playwright install --with-deps chromium
npm test
```

## Interactive UI Mode
```bash
npm run test:ui
```
"""
                zf.writestr("README.md", readme)

            else:
                # Python Suite
                py_code = cls.generate_python_test(target_url, action_traces, session_id)
                zf.writestr("tests/test_api_regression.py", py_code)

                # pytest.ini
                pytest_ini = """[pytest]
addopts = --headed --browser chromium -v
testpaths = tests
"""
                zf.writestr("pytest.ini", pytest_ini)

                # requirements.txt
                reqs = """pytest>=8.0.0
pytest-playwright>=0.4.4
playwright>=1.42.0
"""
                zf.writestr("requirements.txt", reqs)

                # README.md
                readme = f"""# InsightAPI Playwright Python Regression Suite

Auto-generated regression test suite for **{target_url}**.

## Prerequisites
- Python 3.10+

## Quick Start
```bash
pip install -r requirements.txt
playwright install chromium
pytest
```

## Headless Mode in CI/CD
```bash
pytest -o addopts="--browser chromium"
```
"""
                zf.writestr("README.md", readme)

        zip_buf.seek(0)
        return zip_buf.getvalue()
