from typing import List, Dict, Any


class MarkdownExporter:
    """
    Exports captured API endpoints into formatted Markdown documentation files.
    Includes AI-generated summaries, tags, and category labels when available.
    """
    @staticmethod
    def generate_markdown(
        title: str,
        target_url: str,
        captured_endpoints: List[Dict[str, Any]]
    ) -> str:
        """Generates Markdown API Documentation string."""
        lines = [
            f"# API Documentation — {title}",
            "",
            f"> Autogenerated by **InsightAPI AI** on autonomous crawl of `{target_url}`.",
            "",
            "## Summary of Discovered Endpoints",
            "",
            "| Method | Endpoint Route | Status | Category | Auth Required |",
            "|:---:|:---|:---:|:---|:---:|"
        ]

        for ep in captured_endpoints:
            method = ep.get("method", "GET").upper()
            route = ep.get("template_route", "/")
            status = ep.get("status", 200)
            graphql_op = ep.get("graphql_operation_name")
            category = ep.get("ai_endpoint_category", "—")
            display_route = f"{route} *(GraphQL: {graphql_op})*" if (graphql_op and "(" not in route) else route
            lines.append(f"| `{method}` | `{display_route}` | `{status}` | {category} | — |")

        lines.extend([
            "",
            "---",
            "",
            "## Endpoint Details",
            ""
        ])

        for ep in captured_endpoints:
            method = ep.get("method", "GET").upper()
            route = ep.get("template_route", "/")
            url = ep.get("url", target_url + route)
            graphql_op = ep.get("graphql_operation_name")
            ai_summary = ep.get("ai_summary", "")
            ai_tags = ep.get("ai_tags", [])
            ai_category = ep.get("ai_endpoint_category", "")
            confidence = ep.get("confidence", 0)

            detail_title = f"### `{method}` {route}"
            if graphql_op and "(" not in route:
                detail_title += f" — GraphQL Operation: `{graphql_op}`"

            lines.append(detail_title)
            lines.append("")

            # AI-generated description block
            if ai_summary:
                lines.append(f"> {ai_summary}")
                lines.append("")

            meta_parts = []
            if ai_category:
                meta_parts.append(f"**Category:** {ai_category}")
            if ai_tags:
                meta_parts.append(f"**Tags:** {', '.join(f'`{t}`' for t in ai_tags)}")
            if ep.get("is_vision_derived"):
                meta_parts.append("**Source:** `Vision Fallback`")
            if ep.get("triggered_by"):
                trig = ep["triggered_by"]
                ctx = trig.get("form_context") or trig.get("selector") or "Form Submit"
                meta_parts.append(f"**Triggered By:** `{ctx[:35]}`")
            meta_parts.append(f"**Confidence:** `{confidence:.0%}`")
            if meta_parts:
                lines.append(" · ".join(meta_parts))
                lines.append("")

            lines.extend([
                f"* **Target URL**: `{url}`",
                f"* **Observed Status**: `{ep.get('status', 200)}`",
            ])

            if ep.get("related_calls"):
                lines.append(f"* **Related Calls ({len(ep['related_calls'])})**:")
                for rc in ep["related_calls"]:
                    rc_method = rc.get("method", "GET")
                    rc_route = rc.get("template_route", "/")
                    rc_status = rc.get("status", 200)
                    lines.append(f"  * `{rc_method} {rc_route}` (HTTP {rc_status})")

            lines.extend([
                "",
                "#### Example cURL Request",
                "```bash",
                f'curl -X {method} "{url}" \\',
                '  -H "Accept: application/json"',
                "```",
                "",
                "---",
                ""
            ])

        return "\n".join(lines)
