import re
import json
from urllib.parse import urlparse, parse_qs
from typing import List, Dict, Any, Optional


class OpenAPIExporter:
    """
    Exports captured and analyzed API endpoints into valid OpenAPI 3.0.3 specification JSON.

    After the ``AnalyzerNode`` processes raw observations, each endpoint record contains:
    - ``schema``       — merged OpenAPI schema across all observed response bodies
    - ``examples``     — up to 3 redacted ``{request_payload, response_body}`` pairs
    - ``confidence``   — float score (see AnalyzerNode.compute_confidence)
    - ``example_count``— raw observation count used during merging

    This exporter surfaces all of that in the generated spec so that tools like
    Postman, Insomnia, and Stoplight can immediately replay real, observed requests.
    """

    @staticmethod
    def _extract_path_params(route: str) -> List[Dict[str, Any]]:
        """Return OpenAPI ``parameters`` entries for ``{param}`` placeholders in *route*."""
        placeholders = re.findall(r"\{([^}]+)\}", route)
        return [
            {
                "name": p,
                "in": "path",
                "required": True,
                "schema": {"type": "string"},
                "description": f"Dynamic path parameter inferred by InsightAPI",
            }
            for p in placeholders
        ]

    @staticmethod
    def _build_examples_object(
        example_list: List[Dict[str, Any]],
        key: str,
    ) -> Optional[Dict[str, Any]]:
        """
        Build an OpenAPI ``examples`` map from a list of ``{request_payload, response_body}``
        dicts, extracting the field named *key* (``"response_body"`` or ``"request_payload"``).

        Returns ``None`` if no non-null values are found.
        """
        result: Dict[str, Any] = {}
        for idx, pair in enumerate(example_list):
            value = pair.get(key)
            if value is not None:
                result[f"example_{idx}"] = {
                    "summary": f"Observed {'response' if key == 'response_body' else 'request'} {idx + 1}",
                    "value": value,
                }
        return result if result else None

    @staticmethod
    def generate_spec(
        title: str,
        target_url: str,
        captured_endpoints: List[Dict[str, Any]],
        version: str = "1.0.0",
    ) -> Dict[str, Any]:
        """
        Generates an OpenAPI 3.0.3 specification dictionary.

        Each path entry is enriched with:
        - Path parameters derived from ``{placeholder}`` segments in the route.
        - ``examples`` under ``responses[status].content.application/json`` using
          actual captured (and redacted) response payloads.
        - ``requestBody`` with ``examples`` for POST / PUT / PATCH endpoints that
          have observed request payloads.
        - ``x-confidence`` and ``x-example-count`` vendor extensions so tooling
          can surface reliability metadata.
        """
        paths: Dict[str, Any] = {}

        for ep in captured_endpoints:
            full_route = ep.get("template_route", "/")
            parsed_route = urlparse(full_route)
            raw_path = parsed_route.path if parsed_route.path else "/"
            base_route = re.sub(r'\s*\([^)]*\)', '', raw_path).strip()
            method = ep.get("method", "GET").lower()
            status = str(ep.get("status", 200))
            schema = ep.get("schema", {})
            graphql_op = ep.get("graphql_operation_name")
            examples: List[Dict[str, Any]] = ep.get("examples", [])
            confidence: float = ep.get("confidence", 0.85)
            example_count: int = ep.get("example_count", 1)

            # Create distinct OpenAPI path for GraphQL operations
            if graphql_op:
                clean_op_slug = re.sub(r'[^a-zA-Z0-9_]', '_', graphql_op)
                route = f"{base_route.rstrip('/')}/{clean_op_slug}"
                summary = f"GraphQL Operation: {graphql_op}"
                operation_id = f"graphql_{clean_op_slug}"
            else:
                route = base_route
                summary = f"Autogenerated {method.upper()} endpoint for {route}"
                raw_op = f"{method}_{route.replace('/', '_').strip('_')}"
                operation_id = re.sub(r'[^a-zA-Z0-9_]', '_', raw_op)

            if route not in paths:
                paths[route] = {}

            # ── Parameters ─────────────────────────────────────────────────────
            # Path parameters from {placeholder} segments + query string parameters
            parameters: List[Dict[str, Any]] = OpenAPIExporter._extract_path_params(route)
            query_params = parse_qs(parsed_route.query)
            for q_key in query_params:
                parameters.append({
                    "name": q_key,
                    "in": "query",
                    "required": False,
                    "schema": {"type": "string"},
                })

            if method not in paths[route]:
                summary_text = summary
                description_text = ep.get("ai_summary") or f"Autogenerated {method.upper()} endpoint for {route}"
                tags = ep.get("ai_tags") or []
                operation: Dict[str, Any] = {
                    "summary": summary_text,
                    "description": description_text,
                    "operationId": operation_id,
                    "x-confidence": confidence,
                    "x-example-count": example_count,
                    "x-ai-category": ep.get("ai_endpoint_category", ""),
                    "responses": {},
                }
                if ep.get("is_vision_derived"):
                    operation["x-vision-derived"] = True
                if ep.get("triggered_by"):
                    operation["x-triggered-by"] = ep["triggered_by"]
                if ep.get("related_calls"):
                    operation["x-related-calls"] = ep["related_calls"]
                if tags:
                    operation["tags"] = tags
                if parameters:
                    operation["parameters"] = parameters
                paths[route][method] = operation

            # ── Response ───────────────────────────────────────────────────────
            response_content: Dict[str, Any] = {"schema": schema}
            response_examples = OpenAPIExporter._build_examples_object(examples, "response_body")
            if response_examples:
                response_content["examples"] = response_examples

            paths[route][method]["responses"][status] = {
                "description": f"Observed response for HTTP {status}",
                "content": {"application/json": response_content},
            }

            # ── Request Body (POST / PUT / PATCH) ──────────────────────────────
            if method in {"post", "put", "patch"} and "requestBody" not in paths[route][method]:
                request_examples = OpenAPIExporter._build_examples_object(examples, "request_payload")
                req_schema = ep.get("form_inferred_request_schema") or {"type": "object"}
                if request_examples:
                    for pair in examples:
                        payload = pair.get("request_payload")
                        if isinstance(payload, dict):
                            req_schema = {
                                "type": "object",
                                "properties": {k: {"type": "string"} for k in payload},
                            }
                            break

                if req_schema.get("properties") or request_examples:
                    req_content: Dict[str, Any] = {"schema": req_schema}
                    if request_examples:
                        req_content["examples"] = request_examples
                    paths[route][method]["requestBody"] = {
                        "required": True,
                        "content": {
                            "application/json": req_content
                        },
                    }

        spec = {
            "openapi": "3.0.3",
            "info": {
                "title": f"API Specification - {title}",
                "description": (
                    f"Autogenerated by InsightAPI AI from autonomous crawl on {target_url}. "
                    "Schemas are merged across all observed response examples; "
                    "nullable fields were seen as null in at least one observation; "
                    "optional fields were absent in at least one observation."
                ),
                "version": version,
            },
            "servers": [{"url": target_url, "description": "Target Host"}],
            "paths": paths,
        }

        return spec

    @classmethod
    def export_to_json(cls, title: str, target_url: str, captured_endpoints: List[Dict[str, Any]]) -> str:
        """Returns pretty-printed OpenAPI JSON string."""
        spec = cls.generate_spec(title, target_url, captured_endpoints)
        return json.dumps(spec, indent=2)
