import json
from typing import List, Dict, Any
from urllib.parse import urlparse


class PostmanExporter:
    """
    Exports captured API endpoints into official Postman Collection v2.1 specification format.

    Each collection item is enriched with:
    - ``request.body`` — pre-filled with the first observed (redacted) request payload
      so the collection is immediately runnable from Postman without manual editing.
    - ``response`` — up to 3 saved example responses from actual captured payloads,
      including status code, headers, and body.
    """

    @staticmethod
    def generate_collection(
        title: str,
        target_url: str,
        captured_endpoints: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Generates Postman Collection v2.1 dictionary structure."""
        items = []

        for ep in captured_endpoints:
            method = ep.get("method", "GET").upper()
            route = ep.get("template_route", "/")
            url = ep.get("url", target_url)
            parsed_url = urlparse(url)
            graphql_op = ep.get("graphql_operation_name")
            examples: List[Dict[str, Any]] = ep.get("examples", [])
            status: int = ep.get("status", 200)

            if graphql_op:
                item_name = f"{method} {parsed_url.path} — {graphql_op}"
            else:
                item_name = f"{method} {parsed_url.path}"

            # ── Request body ───────────────────────────────────────────────────
            request_body: Dict[str, Any] = {}
            if method in {"POST", "PUT", "PATCH"}:
                # Find the first non-null request payload from examples
                first_payload = next(
                    (pair["request_payload"] for pair in examples if pair.get("request_payload") is not None),
                    None,
                )
                if first_payload is not None:
                    request_body = {
                        "mode": "raw",
                        "raw": json.dumps(first_payload, indent=2),
                        "options": {"raw": {"language": "json"}},
                    }

            item: Dict[str, Any] = {
                "name": item_name,
                "request": {
                    "method": method,
                    "header": [
                        {"key": "Content-Type", "value": "application/json"},
                        {"key": "Accept", "value": "application/json"},
                    ],
                    "url": {
                        "raw": url,
                        "host": [parsed_url.netloc] if parsed_url.netloc else [target_url],
                        "path": [p for p in parsed_url.path.split("/") if p],
                    },
                },
                "response": [],
            }

            if request_body:
                item["request"]["body"] = request_body

            # ── Saved example responses ────────────────────────────────────────
            saved_responses: List[Dict[str, Any]] = []
            for idx, pair in enumerate(examples):
                resp_body = pair.get("response_body")
                if resp_body is None:
                    continue
                body_str = json.dumps(resp_body, indent=2) if isinstance(resp_body, (dict, list)) else str(resp_body)
                saved_responses.append({
                    "name": f"Example {idx + 1}",
                    "originalRequest": item["request"],
                    "status": _http_status_text(status),
                    "code": status,
                    "header": [{"key": "Content-Type", "value": "application/json"}],
                    "body": body_str,
                })

            item["response"] = saved_responses
            items.append(item)

        collection = {
            "info": {
                "name": f"Postman Collection — {title}",
                "description": (
                    f"Autogenerated by InsightAPI AI for {target_url}. "
                    "Request bodies and example responses are pre-filled from actual "
                    "captured (and redacted) network traffic."
                ),
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            },
            "item": items,
        }

        return collection

    @classmethod
    def export_to_json(cls, title: str, target_url: str, captured_endpoints: List[Dict[str, Any]]) -> str:
        """Returns pretty-printed Postman Collection JSON string."""
        collection = cls.generate_collection(title, target_url, captured_endpoints)
        return json.dumps(collection, indent=2)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_STATUS_TEXTS: Dict[int, str] = {
    200: "OK", 201: "Created", 204: "No Content", 400: "Bad Request",
    401: "Unauthorized", 403: "Forbidden", 404: "Not Found",
    422: "Unprocessable Entity", 429: "Too Many Requests",
    500: "Internal Server Error", 503: "Service Unavailable",
}


def _http_status_text(code: int) -> str:
    return _STATUS_TEXTS.get(code, "Unknown")
